
model_description: |
  * v0.0.1: first version
    test-standard: spl: 0.3099, soft_spl: 0.3497, dist: 3.305, success: 0.58

habitat_config: ${oc.env:CHALLENGE_CONFIG_FILE}

# habitat challenge 2022 goals
goal_mapping:
  0: chair
  1: bed
  2: plant
  3: toilet
  4: tv_monitor
  5: sofa

num_goal_classes: 6

log_path: "./Kemono/logs/evaluate/val/v0.0.1/"
device: cuda
eval_num_episodes: 100
skip_to_episode: 0

visualize:
  draw_nav_map: ${oc.env:IS_LOCAL,null} # colorize navigation map
  nav_map_key: nav_map
  render_scene: ${oc.env:IS_LOCAL,null}  # screen must be enabled
  monitoring: ${oc.env:IS_LOCAL,null}  # record mp4
  interact: false  # interact mode (probe semantic results)
  keyboard: false  # enable keyboard control
  waitKey: -1  # -1: no wait, 0: wait forever, 1~: ms
  scale: 0.7
  colors:
    obstacle_color: "#ffffff"
    objgoal_color: "#ff00ff"
    ltg_color: "#ffff00"
    stg_color: null
    collision_color: "#00ffff"
    visited_color: "#ff0000"
    frontier_color: "#228B22"

env:
  env_id: HabitatEnv-v0
  semantic:
    predictor_config:
      ckpt: ./Kemono/weights/my_rednet_ep88_498934.ckpt
      device: ${device}
      goal_scale: 0.5
    goal_mapping: ${goal_mapping}
    colorized: true
  
  semantic_map_builder:
    world_config: # this is used as the base config of map projector
      map_res: 0.03
      map_width: 300 # initial width and height
      map_height: 300
      trunc_height_max: 1.6
      width_offset: 0.0
      height_offset: 0.0
      clip_border: 10
      fill_value: 0
      to_global: true
      device: cuda
    local_config:
      map_res: 0.03
      map_width: 300
      map_height: 300
      width_offset: 150.0 # map_width / 2: center
      height_offset: 0.0
      fill_value: 0
      to_global: false
      center_mode: none
    num_classes: 40
    walkable_labels: [2, 16] # floor, stairs
    ignore_labels: [0, 17, 20, 28, 38] # void, ceiling, towel, lightning, clothes
    layers_labels:
      - [16] # stairs
      - [1, 9, 24] # structure: wall, window, column
      - [30] # railing
      - [4] # door
      - [27] # fireplace
      - [31, 36, 13] # furniture: shelving, furniture, chest_of_drawers
      - [37] # appliances
      - [7] # cabinet
      - [34] # seating
      - [3] # chair
      - [26] # counter
      - [5] # table
      - [10] # sofa
      - [8] # cushion
      - [11] # bed
      - [23, 25] # shower, bathtub
      - [18] # toilet
      - [14] # plant
      - [22] # tv_monitor
    goal_labels:
      3: 9 # chair mp40: custom layer
      11: 14 # bed
      14: 17 # plant
      18: 16 # toilet
      22: 18 # tv_monitor
      10: 12 # sofa
    preprocess_config:
      value_type: raw  # ['onehot', 'raw']
    postprocess_config:
      normalize_value: true # softmax normalize
      force_walkable_height: 0.1
      confidence_decay: 1.0
    color_palette:
      - "#FFFFFF" # background
      - "#E2E2E2" # base layer 0: walkable
      - "#666666" # base layer 1: obstacles
      - "#9edae5" # custom layer 0: stairs
      - "#666666" # custom layer 1: structure
      - "#bd9e39" # custom layer 2: railing
      - "#c5b0d5" # custom layer 3: door
      - "#ad494a" # custom layer 4: fireplace
      - "#8c6d31" # custom layer 5: furniture
      - "#e7cb94" # custom layer 6: appliances
      - "#1f77b4" # custom layer 7: cabinet
      - "#ffbb78" # custom layer 8: seating
      - "#98df8a" # custom layer 9: chair
      - "#a55194" # custom layer10: counter
      - "#ff7f0e" # custom layer11: table
      - "#2ca02c" # custom layer12: sofa
      - "#bcbd22" # custom layer13: cushion
      - "#e377c2" # custom layer14: bed
      - "#393b79" # custom layer15: shower, bathtub
      - "#e7969c" # custom layer16: toilet
      - "#8ca252" # custom layer17: plant
      - "#d6616b" # custom layer18: tv_monitor
      - "#FFFF00" # base layer -1: goal
    goal_mapping: ${goal_mapping}
  
  semantic_map_observer:
    maps_config:
      video_map:
        type: world
        threshold: 0.5
        confidence_thres: 0.75
        use_goal_cat: false
        crop:
          center: camera
          width: 400
          height: 400
        smooth:
          dilate_size: 3
          dilate_iter: 2
          erode_size: 3
          erode_iter: 2
        colorize:
          draw_origin: true
          draw_camera: true
          draw_trajectory: true
          draw_frontier: false

  pretty_renderer:
    # used to render pretty scenes for monitoring
    canvas_config:
      - - input: rgb
          size: [640, 480]
          label: RGB
        - input: seg_color
          size: [640, 480]
          label: Semantics
        - input: video_map
          size: [480, 480]
          label: "Topdown View"
        - input: nav_map
          size: [480, 480]
          label: "Navigation map"
    goal_mapping: ${goal_mapping}
    backend: cv2 # cv2 (faster but ugly) or matplotlib
    dpi: 200 # only available for matplotlib

  monitor:
    # monitoring, output video
    root_dir: "${log_path}monitor/"
    video: True
    video_kwargs:
      interval: 1
      fps: 10

agent:
  # kemono agent config
  seed: 1
  timestep_limit: 500
  clean_stair_map: true # clean noises from stairs
  stair_dilate_size: 7
  stair_erode_size: 8

  # agent controller
  controller:
    map_res: 0.05 # map resolution (meter/px)
    map_size: 1440 # full map size, collision map, visited map
    collision_thres: 0.2 # distance threshold (meter)
    collision_width: 1
    collision_length: 1
    collision_dist: 3
    max_collision_width: 2
    max_collision_length: 1
    max_collision_dist: 4
    block_thres: 10 # thres to execute untrap helper
    turn_angle: 30 # agent turning angle (deg)
    turn_thres: 0.8 # turning thres (%)
    occ_brush_size: 3 # obstacle dilation size

    step_size: 0.20 # meter
    near: 0.25 # meter
    far: 12 # meter (240*0.05)

    walkable_channels: [0, 2] # free, stairs
    class_costs:
      - 1      # walkable: 0 free
      - 100    # walkable: 1 stairs
      - 1000   # 2 collision
      - 100000 # 3 obstacles
      - 100000 # 4 structures
      - 100000 # 5 railing
      - 100000 # 6 door
      - 10000  # >7 others
    non_walkable: 2 # >2 collision are non-walkable

    goal_brush_size: 6 # non-iterative goal dilation
    use_iter_dilate: true # iterative goal dilation
    goal_iter_num: 6 # iteration count
    goal_iter_brush_size: 1 # dilation size
    pad_surroundings: 1 # agent's surrounding pixels
    pad_border: 1 # border pixels

  # keyboard controller
  planners:
    # rule-based planner
    - type: start_up
      actions: [2,2,2,2,2,2,2,2,2,2] # turn left * 10
    - type: points
      map_size: 240
      radius: 0.5657
      angle: 135
      n_points: 4
      local_steps: 25


rl:
  type: sac
  log_path: ./Kemono/logs/train/${.type}_v0/
  habitat_config: ./Kemono/configs/hm3d_rl_train.yaml
  seed: 5632

  envs:
    vec_envs:
      n_envs: 2
      use_subproc: true
      use_gpus: [1, 2]
    rewards:
      step_reward: -0.1
      dist_reward: 1.0
      success_reward: 10.0
      explore_reward: 0.0001
      reduce: null # null, sum, mean
    planner:
      type: continuous
      map_res: 0.05
      map_size: 240
      input_size: 240
      plan_range: [0.1, 0.9]

  agent:

  checkpoint:

  trainer: